backend:
  name: github
  repo: karthiksak/nbclinic
  branch: main
  base_url: https://noblehomeo.vercel.app # URL of Vercel production deployment
  auth_endpoint: api/auth

media_folder: "src/images"
public_folder: "images"

collections:
  - name: "content"
    label: "Site Elements"
    files:
      - file: "src/_data/site.json"
        label: "Global Settings"
        name: "general_settings"
        fields:
          - label: "General Information"
            name: "general"
            widget: "object"
            fields:
              - { label: "Site Title", name: "title", widget: "string" }
              - { label: "Tagline", name: "tagline", widget: "string" }
              - { label: "Phone Number", name: "phone", widget: "string" }
              - { label: "Email Address", name: "email", widget: "string" }
              - { label: "Physical Address", name: "address", widget: "text" }
              - { label: "Google Maps URL", name: "google_maps_embed", widget: "string" }
          - label: "Patient Reviews"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Review Text", name: "text", widget: "text" }
              - { label: "Author Name & Date", name: "author", widget: "string" }
              - { label: "Star Rating (1-5)", name: "stars", widget: "number", value_type: "int", min: 1, max: 5 }
